CREATE DATABASE budget;

CREATE TABLE transactions(
trans_id SERIAL PRIMARY KEY,
transaction_date DATE,
item VARCHAR,
price DOUBLE PRECISION
);

CREATE USER test WITH PASSWORD 'password';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO test;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO test;